apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

  # add default stuff, including default namespaces
  # add some more namespaces to this cluster
resources:
- ../../../../apps/common
- overlays/namespaces
