---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-a
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: AppProject for team a

  sourceRepos:
    - "*"

  destinations:
    - namespace: "team-a-*"
      server: https://kubernetes.default.svc
      name: in-cluster

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  roles:
    # A role which provides read-only access to all applications in the project
    - name: read-write
      description: Grants all required permissions for the team
      policies:
        - p, proj:team-a:admin, applications, *, team-a/*, allow
        - p, proj:team-a:admin, repositories, create, team-a/*, allow
        - p, proj:team-a:admin, repositories, delete, team-a/*, allow
        - p, proj:team-a:admin, repositories, update, team-a/*, allow
      groups:
        - team-a

  # Sync windows restrict when Applications may be synced. https://argo-cd.readthedocs.io/en/stable/user-guide/sync_windows/
  syncWindows:
    - kind: allow
      schedule: "10 1 * * *"
      duration: 1h
      applications:
        - "*-prod"
      manualSync: true
    - kind: deny
      schedule: "0 22 * * *"
      duration: 1h
      namespaces:
        - default
    - kind: allow
      schedule: "0 23 * * *"
      duration: 1h
      clusters:
        - in-cluster

  # By default, apps may sync to any cluster specified under the `destinations` field, even if they are not
  # scoped to this project. Set the following field to `true` to restrict apps in this cluster to only clusters
  # scoped to this project.
  permitOnlyProjectScopedClusters: true

  # When using Applications-in-any-namespace, this field determines which namespaces this AppProject permits
  # Applications to reside in. Details: https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/
  # sourceNamespaces:
  #   - "argocd-apps-*"
