---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foo

resources:
  - ../../../../apps/cluster-configs

patches:
  - target:
      group: ""
      version: v1
      kind: Namespace
      name: cluster-configs
    path: patch.yaml
